name: dev

on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "!**.md"
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "!**.md"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Md2md
        run: |
          sudo npm install md2md -g
          goover
          rm -rf doc_from/*
          mv doc_to site

      - name: Delete And Push
        run: |
          cd ../
          git clone https://.:${{ secrets.P_GITHUB_TOKEN }}@github.com/nameczz/a-project.git target
          git config --global user.email "nameczz@126.com"
          git config --global user.name "nameczz"
          cd target
          git checkout -b ${{ steps.extract_branch.outputs.branch }}
          rm -rf *
          cd ../
          cp -avr ./test-doc/** ./target/
          cd target
          git add .
          git commit -m "Bot add"
          git push -f origin ${{ steps.extract_branch.outputs.branch }}
